version: '3'
services:
  php:
    build: ./docker/php/8.2
    entrypoint: php
    volumes:
      - .:/home/ubuntu/app
    working_dir: /home/ubuntu/app

  composer:
    build: ./docker/php/8.2
    entrypoint: composer
    volumes:
      - .:/home/ubuntu/app
    working_dir: /home/ubuntu/app
    environment:
      - "XDEBUG_MODE=coverage"

  php81:
    build: ./docker/php/8.1
    entrypoint: php
    volumes:
      - .:/home/ubuntu/app
    working_dir: /home/ubuntu/app

  composer81:
    build: ./docker/php/8.1
    entrypoint: composer
    volumes:
      - .:/home/ubuntu/app
    working_dir: /home/ubuntu/app
    environment:
      - "XDEBUG_MODE=coverage"
